volumes:
  logs:
    driver: local

services:
  slim:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      docker: "true"
      # GTM_TAG: ''
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10
    ports:
      - 8080:8080
    restart: always
      - logs:/var/www/logs
